name: Trivy Container Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      # リポジトリのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker Compose のセットアップ
      - name: Start Docker Compose services
        run: docker compose up -d

      # Trivyでコンテナイメージをスキャン
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with: 
            image-ref: 'awesometodo:latest'
            format: 'table'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'HIGH,CRITICAL'
            output: 'trivy-report.txt'

      # スキャンレポートをGitHub Actionsのアーティファクトとして保存
      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-report.txt
