name: ZAP Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read            # リポジトリの内容を読み取る
  security-events: write    # セキュリティスキャン結果の記録
  issues: write             # Issuesへの追加

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: ローカルWebサーバーをバックグラウンドで起動
        run: |
          php -S localhost:8000 -t src &
          sleep 3

      - name: ZAP Scan
        uses: zaproxy/action-af@v0.2.0
        with:
            # 作成した自動化プランのファイルを指定
            plan: 'tmp/zap_scan.yml'
 
      - name: スキャン結果をアーティファクトとして保存
        uses: actions/upload-artifact@v4
        with:
             name: zap-report   # レポート名を指定
             path: |
              ${{ github.workspace }}/zap_report.html
              ${{ github.workspace }}/zap_report/

      - name: スキャン結果をIssuesに投稿
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "ZAP セキュリティスキャンレポート",
              body: `ZAP スキャンの結果が生成されました。\n\n[レポートをダウンロード](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`
            });