name: ZAP API Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read            # リポジトリの内容を読み取る
  security-events: write    # セキュリティスキャン結果の記録
  issues: write             # Issuesへの追加

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: ローカルWebサーバーをバックグラウンドで起動
        run: |
          php -S localhost:8000 -t src &
          sleep 3

      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.9.0
        with:
          target: 'http://localhost:8000/docs/openapi.yaml'
